words = ["the ","door ","shrek ","tree ","joe ","a ","in","pharaoh","mama ","as ","was ","running ","if ","with ","and "]
print(words[2])
print(words[10])
print(words[6])
print(words[5])
print(words[3])
print(words[13])
print(words[0])
print(words[7])
print(words[14])
print(words[4])
print(words[8])
print(words[11])
print(words[5])
print(words[1])
